# Generated by Django 5.1.3 on 2024-11-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_slug',
        ),
    ]
