# Generated by Django 5.1.3 on 2024-11-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_doctor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
